# Generated by Django 2.2.2 on 2019-08-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='place_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
