# Generated by Django 2.2.2 on 2019-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_auto_20190803_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
