# Generated by Django 3.0.3 on 2021-01-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='tblContact',
        ),
    ]
